### ISSUE TITLE
[Ajuste] Alterar texto "Segundo lote"

### ISSUE THREAD

**Issue by joaopvilla** [isa17/isa17-hotsite#22]
Alterar o texto "Segundo lote" para "Primeiro lote"

<img width="628" alt="screen shot 2017-01-17 at 09 24 32" src="https://cloud.githubusercontent.com/assets/17101231/22018612/c7fe9142-dc96-11e6-833b-d69692c8e136.png">

**Comment by joaopvilla** [comment]
@prbprado essa aqui :)

**Comment by prbprado** [comment]
Feitoooo
https://github.com/isa17/isa17-hotsite/commit/1fea53b8fc63dfbc021c3cd8dbc2dd34d3bf8906
